### ISSUE TITLE
operator-installer chart failing trying to install kubevirt

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/helm-charts#576]
The verifier pods are all crashing with a python error:

```
Get Subscription (kubevirt-hyperconverged) UID
- Subscription (kubevirt-hyperconverged) UID: 529ac0e5-5ef7-4653-ba14-058aaf4db6fd
Find InstallPlan in Namespace (openshift-cnv) for CSV (kubevirt-hyperconverged-operator.v4.16.2) with Subscription ($529ac0e5-5ef7-4653-ba14-058aaf4db6fd) owner
- Found InstallPlan: install-qxq24
Verify InstallPlan and CSV installed:
- InstallPlan name: install-qxq24
- InstallPlan CSVs: ['kubevirt-hyperconverged-operator.v4.16.2']
- Verify InstallPlan (install-qxq24) installed attempt (0 of 1) success, current phase: Complete
Traceback (most recent call last):
File "/scripts/installplan-verifier.py", line 52, in <module>
1,
File "/scripts/..2024_09_26_11_19_02.3857035676/installplan_utils.py", line 184, in verify_installplan_and_csv_installed
csvs_installed = csv.model.status.conditions.can_match(
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by InfoSec812** [comment]
NVM, it was a permissions problem
